### ISSUE TITLE
code snippet

### ISSUE THREAD

**Issue by asifdev124** [RBoelter/mostViewed#10]
@NateWr @nmueller18 @RBoelter 

What code snippet I need to use if I want to place it in template manually? I dont want the position you have specified, i want to call the  most viewed articles at certain area of the page.. any code to use? thanks

**Comment by RBoelter** [comment]
You have to use JavaScript/CSS to reposition the plugin. There is no other way to do this because it uses a hook with a fixed position. I do the same for the "[display location](https://github.com/RBoelter/mostViewed/blob/master/templates/mostViewed.tpl#L1-L14)" option. The easiest way is to create an empty div at the target position and then copy and paste the contents of the .most-viewed div into the target div via JavaScript.
