### ISSUE TITLE
Upgrade plugin to work under OJS 3.4

### ISSUE THREAD

**Issue by jonasraoni** [RBoelter/mostViewed#14]
**Describe the problem you would like to solve**
The plugin needs some updates to work properly under OJS 3.4.

I'll be working on it, so I'm planning to come back with a PR shortly.

**Comment by jonasraoni** [comment]
@RBoelter here's a PR:
- https://github.com/RBoelter/mostViewed/pull/15

I'll be testing on the next days, but so far, it seems to be working fine (just saved the settings, changed some things, checked the scheduled task).

**Comment by RBoelter** [comment]
Thanks for your PR. I created a branch stable-3_3_x for the 3.3 LTS version, because I assume that this plugin worked with OJS 3.3.x. Your changes are now in the main branch. Do you also add the entry in the PKP-Plugin Gallery? My pkp-plugin CLI tool is unfortunately not working anymore, apparently due to the Github Basic Auth changes.

I finished my quote plugin for (https://github.com/RBoelter/citations) OJS 3.4.x a while ago, but I forgot to add the new version to the plugin gallery.

**Comment by jonasraoni** [comment]
Thanks! I'll check how to get it into the plugin gallery.

About the PR... The "view count" is considering `Application::ASSOC_TYPE_SUBMISSION` and `Application::ASSOC_TYPE_SUBMISSION_FILE` (downloads of galleys)... Somehow I think it's ok to join all these numbers. But if you don't agree (I didn't see if this is a breaking change regarding OJS < 3.4), it needs to be fixed (I'm open to push another PR as well).

**Comment by jonasraoni** [comment]
@RBoelter did you have any luck to publish the package? 😁

**Comment by jonasraoni** [comment]
Here it's just missing to publish the package, but I'll close.
